export const raftrURL = "https://go.raftr.com/fnSG"
export const githubURL = "https://github.com/oxycs"
export const instaURL = "https://www.instagram.com/oxycs/"
export const discordURL = "https://discord.gg/H2hHhsPwne"
export const emailAddr = "mailto:csc@oxy.edu"
export const emailPlaintext = "csc@oxy.edu"
export const icalJSON = "https://ical.csc.oxy.edu/"
export const linkedInURL = "https://www.linkedin.com/groups/13101529/"